---
categories:
- ""
- ""
date: '2020-10-01T21:28:43-05:00'
description: "Investigating the change in average temperature"
draft: false
image: risk_vs_return.jpeg
keywords: ""
slug: climate
title: Climate Change
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies you need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<pre class="r"><code>tidyweather &lt;- weather %&gt;%
  select(-c(&quot;J-D&quot;, &quot;D-N&quot;, &quot;DJF&quot;, &quot;MAM&quot;, &quot;JJA&quot;, &quot;SON&quot;)) %&gt;% # select relevant columns
  pivot_longer(cols = 2:13, names_to = &quot;Month&quot;, values_to = &quot;delta&quot;) # make data frame tidy</code></pre>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trendline. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         month = month(date), #had to get rid of label = true. TA advised could be a package loading problem
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies drastically increasing over time&quot;
  )</code></pre>
<p><img src="/projects/climate/climate_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Is the effect of increasing temperature more pronounced in some months? Use <code>facet_wrap()</code> to produce a seperate scatter plot for each month, again with a smoothing line. Your chart should human-readable labels; that is, each month should be labeled “Jan”, “Feb”, “Mar” (full or abbreviated month names are fine), not <code>1</code>, <code>2</code>, <code>3</code>.</p>
<p><img src="/projects/climate/climate_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<ul>
<li>We can see that the weather anomalies are more pronounced in the winter months!</li>
</ul>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calcuialtes a temperature anomaly, as difference form the base periof of 1951-1980. The code below creates a new data frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We remove data before 1800 and before using <code>filter</code>. Then, we use the <code>mutate</code> function to create a new variable <code>interval</code> which contains information on which period each observation belongs to. We can assign the different periods using <code>case_when()</code>.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in. Set <code>fill</code> to <code>interval</code> to group and colour the data by different time periods.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with transparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;         #changing y-axis label 
  )</code></pre>
<p><img src="/projects/climate/climate_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta = mean(delta, na.rm=TRUE)) 

#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;
  )                         </code></pre>
<p><img src="/projects/climate/climate_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>I will construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 
  # clean NAs and choose the interval 2011-present
  drop_na(delta) %&gt;% 
  filter(Year &gt;= 2011) %&gt;% 
  # calculate yearly mean temperature deviation (delta) 
  group_by(Year) %&gt;% 
  summarise(year_mean_delta = mean(delta)) %&gt;%    
  
  # Confidence Interval (CI) using the formula mean +- MoE
  summarise(mean_delta = mean(year_mean_delta), # calculate summary statistics for yearly mean temperature deviation (delta) 
            sd_delta = sd(year_mean_delta),
            count = n(),
            t_critical = qt(0.975, count-1),  # get t-critical value with (n-1) degrees of freedom
            se_delta = sd(year_mean_delta)/sqrt(count), # calculate mean, SD, count, SE, lower/upper 95% CI
            margin_of_error = t_critical * se_delta,
            delta_low = mean_delta - margin_of_error,
            delta_high = mean_delta + margin_of_error)


formula_ci</code></pre>
<pre><code>## # A tibble: 1 x 8
##   mean_delta sd_delta count t_critical se_delta margin_of_error delta_low
##        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt;     &lt;dbl&gt;
## 1      0.973    0.204     9       2.31   0.0680           0.157     0.816
## # … with 1 more variable: delta_high &lt;dbl&gt;</code></pre>
<pre class="r"><code>set.seed(1234)

boot_yearly_mean_delta &lt;- comparison %&gt;%
  
  # Get rid of NAs in 2019
  drop_na(delta) %&gt;% 
  
  # Choose only  2011 and following
  filter(Year &gt;= 2011) %&gt;%
  
  # Create yearly mean deltas
  group_by(Year) %&gt;% 
  summarise(year_mean_delta = mean(delta)) %&gt;%
  
  # Specify the variable of interest
  specify(response = year_mean_delta) %&gt;%
  
  # Generate a bunch of bootstrap samples
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  
  # Find the mean of each sample
  calculate(stat = &quot;mean&quot;)

# Calculate bootstrap method confidence intervals
percentile_ci &lt;- boot_yearly_mean_delta %&gt;% 
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)
percentile_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.855     1.10</code></pre>
<p>In the above sections, the confidence interval has been calculated using 2 different method: using CI formula and using bootstrap. In the CI formula method, each year’s annual delta has been calculated by taking the arithmetic mean of all months’ delta in that corresponding year. This yields a total of 9 observations from 2011 until 2019. Then, the standard deviation of the data and standard error of the mean are calculated, and then combined with a t-statistic approximation to obtain a 95% confidence interval for the average annual delta. Meanwhile, in the bootstrap method, repeated samples are taken from the data to provide an estimate of the average annual delta. Using the 1st method, we are 95% confident that the actual average is between 0.816 - 1.13. Using the 2nd method, the confidence interval is narrower: 0.855 - 1.1, see the first plot below. Here, the bootstrap distribution is quite close to normal distribution, as is demonstrated in the second plot below, so the 2 confidence intervals should be similar to some extent.</p>
<pre class="r"><code># Visualise bootstrap CI vs formula CI
visualize(boot_yearly_mean_delta) +
  shade_ci(endpoints = percentile_ci,fill = &quot;yellow&quot;)+
  labs(title=&#39;Bootstrap CI for Yearly Mean Temperature Deviation narrower than Formula CI&#39;,
       subtitle = &#39;Formula CI shown with dotted red lines, Bootstrap CI in green&#39;)+
  geom_vline(xintercept = formula_ci$delta_low, colour = &quot;red&quot;, linetype=&quot;dashed&quot;, size=1.2)+
  geom_vline(xintercept = formula_ci$delta_high, colour = &quot;red&quot;, linetype=&quot;dashed&quot;, size=1.2)+
  theme_bw()+
  NULL</code></pre>
<p><img src="/projects/climate/climate_files/figure-html/visualise_bootstrap_and_formula-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code># compare bootstrap distribution with a Normal distribution with parameters estimated from the sample
ggplot(boot_yearly_mean_delta, aes(x = stat)) +
  geom_density(color=&quot;blue&quot;) +
  stat_function(
    fun = dnorm,
    color = &quot;red&quot;,
    size = 2,
    args = list(mean = formula_ci$mean_delta, sd = formula_ci$se_delta)
  )+
  theme_bw()+
  labs(title = &quot;The Bootstrap distribution is close to a Normal distribution&quot;,
       x= &#39;Average rating&#39;, y = &quot;&quot;)+
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  NULL</code></pre>
<p><img src="/projects/climate/climate_files/figure-html/visualise_bootstrap_and_formula-2.png" width="648" style="display: block; margin: auto;" /></p>
</div>
</div>
